basePath: /v1
definitions:
  handler.errorResponse:
    properties:
      message:
        type: string
    type: object
  handler.getAllOrdersResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/models.Order'
        type: array
    type: object
  models.Delivery:
    properties:
      address:
        type: string
      city:
        type: string
      email:
        type: string
      name:
        type: string
      phone:
        type: string
      region:
        type: string
      zip:
        type: string
    type: object
  models.Item:
    properties:
      brand:
        type: string
      chrt_id:
        type: integer
      name:
        type: string
      nm_id:
        type: integer
      price:
        type: integer
      rid:
        type: string
      sale:
        type: integer
      size:
        type: string
      status:
        type: integer
      total_price:
        type: number
      track_number:
        type: string
    type: object
  models.Order:
    properties:
      customer_id:
        type: string
      date_created:
        type: string
      delivery:
        $ref: '#/definitions/models.Delivery'
      delivery_service:
        type: string
      entry:
        type: string
      internal_signature:
        type: string
      items:
        items:
          $ref: '#/definitions/models.Item'
        type: array
      locale:
        type: string
      oof_shard:
        type: string
      order_uid:
        type: string
      payment:
        $ref: '#/definitions/models.Payment'
      shard_key:
        type: string
      sm_id:
        type: integer
      track_number:
        type: string
    type: object
  models.Payment:
    properties:
      amount:
        type: number
      bank:
        type: string
      currency:
        type: string
      custom_fee:
        type: integer
      delivery_cost:
        type: integer
      goods_total:
        type: number
      payment_dt:
        type: integer
      provider:
        type: string
      request_id:
        type: string
      transaction:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@mail.io
    name: API Support
    url: https://github.com/YuStep/
  description: This is a simple RESTful Service API written in Go using Gin web framework,
    PostgreSQL database,NATS queue with in-memory caching.
  license:
    name: MIT
    url: https://github.com/YuStep/wbl0/blob/main/LICENSE
  title: Go WB API
  version: "1.0"
paths:
  /order:
    get:
      consumes:
      - application/json
      description: get all orders
      operationId: get-all-orders
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.getAllOrdersResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Get All Orders
      tags:
      - Orders
  /order/:id:
    get:
      consumes:
      - application/json
      description: get order by id
      operationId: get-order-by-id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Order'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Get Order By Id
      tags:
      - Orders
swagger: "2.0"
